[build]
target = "index.html"
release = true
dist = "../dist"
public_url = "./"

[[hooks]]
# This hook example shows all the current available fields. It will execute the equivalent of
# typing "echo Hello Trunk!" right at the start of the build process (even before the HTML file
# is read). By default, the command is spawned directly and no shell is used.
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "cd tailwind-yew-builder && docker-compose up prod"]

